---
# --------------------------- #
#   User Site Configuration   #
# --------------------------- #

url: http://franklinchen.com
title: Franklin Chen's grain of sand
subtitle: Infinity in the palm of my hand
author: Franklin Chen
description: Blog of Franklin Chen

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/FranklinChen
subscribe_email: http://feedburner.google.com/fb/a/mailverify?uri=FranklinChen
category_feeds: true
# RSS feeds can list your email address if you like
email: franklinchen@franklinchen.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
permalink: /blog/:year/:month/:day/:title/

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: FranklinChen
github_repo_count: 4
github_skip_forks: false

# Twitter
twitter_user: franklinchen
twitter_show_replies: true
twitter_show_follower_count: true

# Google+
google_plus_one: true

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_user: 100967806642012078047

# Pinboard
#pinboard_user: franklinchen

# Delicious
#delicious_user: franklinchen

# Disqus Comments
disqus_short_name: franklinchen
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-24980509-1

# Facebook Like
facebook_like: true
