---
# --------------------------- #
#   User Site Configuration   #
# --------------------------- #

url: http://franklinchen.com
title: Franklin Chen's grain of sand
subtitle: Infinity in the palm of my hand
author: Franklin Chen
description: Blog of Franklin Chen

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/FranklinChen
subscribe_email: http://feedburner.google.com/fb/a/mailverify?uri=FranklinChen
category_feeds: true
# RSS feeds can list your email address if you like
email: franklinchen@franklinchen.com

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: blog_index.html
page_sidebar: page.html
post_sidebar: post.html

use_comments: true

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
# Note: I use blog
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_repos:
  user: FranklinChen

# Twitter
twitter:
  user: franklinchen

  follow-button:
    follower_count: true

# Google Plus Profile
googleplus:
  user: 100967806642012078047
  plus_one: true


# Pinboard
#pinboard:
#  user: franklinchen

# Delicious
#delicious_user: franklinchen

# Disqus Comments
disqus_short_name: franklinchen
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-24980509-1

# Facebook Like
facebook_like: true

adn:
  user: FranklinChen
